modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="NexusMC"
description='''A cinematic, traversal-first world generator for NexusMC.'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="natures_spirit"
type="optional"
versionRange="[2.2.5,2.3)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="nexus_mobs"
type="optional"
versionRange="[0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="sodium"
type="optional"
versionRange="[0.8.12,0.9)"
ordering="AFTER"
side="CLIENT"
